#ifndef CHRONOS_DISASM_H
#define CHRONOS_DISASM_H

#include "bytecode.h"

// Prints the raw generated bytecode instructions to the console
void disassemble_bytecode(const Instruction* code, int count);

#endif // CHRONOS_DISASM_H
